# yhub info "Explain to me about WRD" --format json
# yhub on WRD go test ./...
# yhub list
# yhub validate
# yhub clone all
# yhub clone group hello foo
# yhub clone repo WRD
# yhub unclone all
# yhub unclone group dynamic-routing
# yhub unclone repo WRD BR

repositories_dir = "repos"
default_platform = "github"
default_protocol = "ssh"

profiles = ["personal", "work"]

[platforms.company]
host = "git.company.com"

# Hello

[[groups.hello]]
profile    = "personal"
repository = "willpinha/world"
name       = "world"
alias      = "WRD"
# platform = "gitlab"
# protocol = "https"

# Foo

[[groups.foo]]
profile    = "work"
repository = "willpinha/bar"
name       = "bar"
alias      = "BR"
